---
- name: Gather facts
  ansible.builtin.gather_facts: {}

- name: Include OS specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "{{ role_path }}/vars/"

- name: Include EDA installation
  ansible.builtin.include_tasks: install_eda.yml
  when: eda_install_eda
